name: Réalisation des tests
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Installation python
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: Installation des dependances
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest
      - name: Réalisation des tests
        run: |
          pytest test_auto.py